apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
      - name: invoice
        image: invoice-service:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  selector:
    app: invoice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: LoadBalancer
